# Generated by Django 4.2.4 on 2023-08-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('can_change_last_name', 'Can change last_name')]},
        ),
    ]
