# Generated by Django 4.2.4 on 2023-09-01 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_person_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuCategories',
            new_name='MenuCategory',
        ),
    ]
